### ISSUE TITLE
Is it available on Telegram?

### ISSUE THREAD

**Issue by giovannibonetti** [zeshuaro/telegram-pdf-bot#121]
This seems like a great project. Is it available on Telegram yet? I couldn't find it.

**Comment by zeshuaro** [comment]
Yes the bot is available on Telegram. You can simply look up `pdfbot` on Telegram or through here https://t.me/pdfbot

**Comment by giovannibonetti** [comment]
What do you think about advertising it in this repo?

![Screenshot 2020-05-14 02 17 15](https://user-images.githubusercontent.com/3451581/81895662-290d0a00-9589-11ea-8d92-148364e8f043.png)

**Comment by zeshuaro** [comment]
Done, thanks for the suggestion!

**Comment by giovannibonetti** [comment]
You're welcome! 😀
