### ISSUE TITLE
Can you simplify the database part ?

### ISSUE THREAD

**Issue by telegrambotdev** [zeshuaro/telegram-pdf-bot#132]
i am stuck at creating `GCP and enabble Datastore`.so i cant fill GCP CRED & GCP TOKEN ' in env var.

can you exactly say the steps which i have to do ? i tried on google cloud and didnt get succeed.

![IMG_20200717_190927_476](https://user-images.githubusercontent.com/20116017/87792226-36809200-c861-11ea-972b-66c484ab35c0.jpg)

anyway your bot is awsome.Thanks in advance

**Comment by zeshuaro** [comment]
You'll need a GCP service account key file and specify the path to that key file in `GCP_KEY_FILE`

**Comment by telegrambotdev** [comment]
> You'll need a GCP service account key file and specify the path to that key file in `GCP_KEY_FILE`

yeah i got the key file.can i place in the root directory of repo ? 

and the path will be what ?

**Comment by zeshuaro** [comment]
Yes you can, then the path will be `path/to/repo/key_file_name`

**Comment by telegrambotdev** [comment]
> Yes you can, then the path will be `path/to/repo/key_file_name`

I tried and getting `GCP-KEY-FILE` error

for more info i am adding my configs

Files in the Directory
![IMG_20200721_230537_868](https://user-images.githubusercontent.com/20116017/88087537-b5016a80-cba6-11ea-96af-41c7c1c156ee.jpg)

env vars in the .env file 


![IMG_20200721_231513_301](https://user-images.githubusercontent.com/20116017/88088461-1118be80-cba8-11ea-9125-7f8c845cd20d.jpg)

Sample Dockerfile

![IMG_20200721_230212_882](https://user-images.githubusercontent.com/20116017/88088598-4ae9c500-cba8-11ea-999a-7b207eee2ff4.jpg)


While running on docker this issue produces

![IMG_20200721_230302_891](https://user-images.githubusercontent.com/20116017/88088474-17a73600-cba8-11ea-995a-8e37d0e74809.jpg)

**Comment by telegrambotdev** [comment]
in start.sh i execute `python bot.py`

can you mention what error is this ?

**Comment by telegrambotdev** [comment]
![IMG_20200722_075725_527](https://user-images.githubusercontent.com/20116017/88127402-22d28400-cbf1-11ea-9877-3f9f93b9f567.jpg)
![Uploading IMG_20200722_075729_123.jpg…]()
