### ISSUE TITLE
Adding Heroku Support 

### ISSUE THREAD

**Issue by bhardwajjEE** [zeshuaro/telegram-pdf-bot#164]
Adding that Heroku Button Will be great help for lazy peoples like me ..😅

(https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy)

**Comment by zeshuaro** [comment]
The bot relies on some additional services to run, e.g. Google Datastore, which can't be configured automatically simply by a Heroku Deploy Button.

**Comment by ZurMaD** [comment]
I'll take a closer look in this. I'll try to create a Heroku image to deploy easily
