### ISSUE TITLE
OCR on pdfs

### ISSUE THREAD

**Issue by harshil21** [zeshuaro/telegram-pdf-bot#582]
The readme of the repo says:
`Add text layers to PDF files to make them searchable with text`

However, I cannot find such a function in pdfbot, I can see there is a `ocrmypdf` dependency here, but how can one use this in [@pdfbot](https://t.me/pdfbot)?

**Comment by zeshuaro** [comment]
Hey @harshil21, after sending a PDF file to the bot, simply select the OCR option 🙂

**Comment by harshil21** [comment]
Ah sorry, I expected a command for the OCR. Thanks for clarifying!
